### ISSUE TITLE
Not compatible with python 3.10.12

### ISSUE THREAD

**Issue by MateuszJed** [CDPTechnologies/PythonCDPClient#13]
Python version on Ubuntu 22.04 
Python == 3.10.12

Exception ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
Traceback (most recent call last):
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/bin/behave", line 8, in <module>
    sys.exit(main())
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/behave/__main__.py", line 183, in main
    return run_behave(config)
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/behave/runner.py", line 804, in run
    return self.run_with_paths()
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/behave/runner.py", line 808, in run_with_paths
    self.load_hooks()
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/behave/runner.py", line 784, in load_hooks
    exec_file(hooks_path, self.hooks)
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/behave/runner_util.py", line 386, in exec_file
    exec(code, globals_, locals_)
  File "environment.py", line 8, in <module>
    from cdp_client import cdp
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/cdp_client/cdp.py", line 1, in <module>
    from promise import Promise
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/promise/__init__.py", line 18, in <module>
    from .promise import (
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/promise/promise.py", line 16, in <module>
    from .promise_list import PromiseList
  File "/home/mateusz/CDPStudioWorkspace/systems/Testing/pyEnv/lib/python3.10/site-packages/promise/promise_list.py", line 2, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by nuustik** [comment]
fixed
